language: python
sudo: false
python:
  - "2.7.6"
  - "3.6"
install:
  - pip install -U pip wheel
  - pip install -U setuptools
script:
  - make flake8
  - make
notifications:
  slack: ccnmtl:GizSNscLWJLldjQrffB8mwgm
