# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 20:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170116_1145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['name']},
        ),
    ]
