# Generated by Django 2.2.24 on 2021-11-23 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20170504_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='message',
            field=models.TextField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='link',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='history',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='information',
            name='infoType',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='information',
            name='internalName',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='performedtest',
            name='paramString',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='performedtest',
            name='testDetails',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_passwd',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_type',
            field=models.CharField(choices=[('AD', 'Administrator'), ('TE', 'Teacher'), ('ST', 'Student')], max_length=2),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tmp_passwd',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
